app:
  kelvin:
    data_types: []
    inputs:
      - data_type: raw.float32
        name: input_metric
        sources:
          - asset_names: [ emulation ]
    language:
      python:
        entry_point: data_labeling_app.data_labeling_app:App
        requirements: requirements.txt
      type: python
  type: kelvin
info:
  description: Create a data label based on certain criteria
  name: data-labeling-app
  title: data-labeling-app
  version: 1.0.0
spec_version: 4.0.0
system:
  environment_vars:
    - name: ACP_NAME
      value: squad4-acp1
    - name: METRIC_SOURCE
      value: rpa-driver-downstream-data
    - name: METRIC_KEY
      value: ns=2;s=pump_intake_temperature
    - name: METRIC_TYPE
      value: raw.float32
    - name: LABEL_NAME
      value: metric-above-threshold
    - name: METRIC_THRESHOLD
      value: '10'
    - name: URL
      value: https://demo.kelvininc.com
    - name: DLSUSER
      value: <% secrets.jumpsuser %>
    - name: DLPASSWORD
      value: <% secrets.jumpspassword %>
  privileged: false
