name: complex.config
version: 0.0.1
class_name: ComplexConfig
description:  "Complex config object used to encapsulate configurations"
fields:
  - name: min_threshold
    description: "The minimum accepted value"
    type: float
  - name: max_threshold
    description: "The maximum accepted value"
    type: float
  - name: rejection_messages
    description: "A list of messages to output in case the vaslue is rejected"
    type: string
    array: true
  - name: success_message
    description: "The correct message to pass in case of success"
    type: string
