app:
  kelvin:
    core:
      data_models:
        - name: raw.float32
          version: 2.0.0
        - name: raw.int32
          version: 2.0.0

      interface:
        client:
          args: []
          executable: run_app
          period: 15.0
          spawn: true
        type: client

      uploader:
        enabled: false
        host: https://localhost
        interval: 30
        backoff: 2
        max_backoff: 60
        batch: 5000
        dir: ./storage
        acp_name: acp_name
        source: consumer
        state_file: kcore-uploader.state

      storage:
        enabled: false
        retention: 2629800
        retention_check_max_freq: 60
        buffer_flush_interval: 100
        buffer_max: 16000
        error_wait: 10
        type: extremedb
        extremedb:
          dir: ./storage
          db_name: kelvindb
          memory_database_size: 2097152
          cache_size: 8388608
          memory_page_size: 128
          disk_page_size: 4096
          select_limit: 5000
          update_values: false
          max_startup_errors: 5

      language:
        python:
          entry_point: consumer.consumer:App
          requirements: requirements.txt
        type: python

      runtime:
        historize_inputs: false
        historize_outputs: true
        type: opcua

      parameters: []

      connections:
        - name: remoteproducer
          type: opcua
          opcua:
            endpoint: opc.tcp://producer.app:48010
            registry_map:
              parameters: []
              inputs:
                - name: temperature_in_celsius
                  node: ns=2;s=temperature_in_celsius
                - name: temperature_in_celsius_int
                  node: ns=2;s=temperature_in_celsius_int
                - name: measure_in_cm
                  node: ns=2;s=measure_in_cm
                - name: measure_in_cm_int
                  node: ns=2;s=measure_in_cm_int
              outputs: []
        - name: myconnection
          type: opcua
          opcua:
            endpoint: opc.tcp://localhost:48010
            registry_map:
              parameters: []
              inputs: []
              outputs:
                - name: temperature_in_fahrenheit
                  node: ns=2;s=temperature_in_fahrenheit
                - name: temperature_in_fahrenheit_int
                  node: ns=2;s=temperature_in_fahrenheit_int
                - name: measure_in_inches
                  node: ns=2;s=measure_in_inches
                - name: measure_in_inches_int
                  node: ns=2;s=measure_in_inches_int

      inputs:
        - name: temperature_in_celsius
          data_model: raw.float32
        - name: temperature_in_celsius_int
          data_model: raw.int32
        - name: measure_in_cm
          data_model: raw.float32
        - name: measure_in_cm_int
          data_model: raw.int32
      outputs:
        - name: temperature_in_fahrenheit
          data_model: raw.float32
        - name: temperature_in_fahrenheit_int
          data_model: raw.int32
        - name: measure_in_inches
          data_model: raw.float32
        - name: measure_in_inches_int
          data_model: raw.int32

      version: 4.0.0
    system_packages: []

  type: kelvin

info:
  description: Data Consumer
  name: consumer
  title: Data Consumer
  version: 1.0.1
spec_version: 1.0.0
