app:
  kelvin:
    data_types: [ ]
    inputs:
      - data_type: raw.float32
        name: setpoint.temperature
        sources:
          - asset_names: [ emulation ]
            workload_names: [ ]
      - data_type: raw.uint64
        name: setpoint.humidity
        sources:
          - asset_names: [ emulation ]
            workload_names: [ ]
      - data_type: raw.int32
        name: setpoint.rpm
        sources:
          - asset_names: [ emulation ]
            workload_names: [ ]
    language:
      python:
        entry_point: hvac_system.hvac_system:App
        requirements: requirements.txt
      type: python
  type: kelvin
info:
  description: hvac-system
  name: hvac-system
  title: hvac-system
  version: 1.0.0
spec_version: 2.0.0
