app:
  kelvin:
    language:
      python:
        entry_point: producer.producer:App
        requirements: requirements.txt
      type: python
    outputs:
      - data_type: raw.float32
        name: temperature_in_celsius
        targets:
          - asset_names: [emulation]
      - data_type: raw.int32
        name: temperature_in_celsius_int
        targets:
          - asset_names: [emulation]
      - data_type: raw.float32
        name: measure_in_cm
        targets:
          - asset_names: [emulation]
      - data_type: raw.int32
        name: measure_in_cm_int
        targets:
          - asset_names: [emulation]
    configuration:
      enabled: true
      min: 0
      max: 45
    system_packages:
      - vim
  type: kelvin
info:
  description: Data Producer
  name: producer
  title: Data Producer
  version: 1.0.2
spec_version: 2.0.0
