app:
  kelvin:
    configuration:
      enabled: true
      max: 45
      min: 0
    language:
      python:
        entry_point: 'producer.producer:App'
        requirements: requirements.txt
      type: python
    outputs:
      - data_type: raw.float32
        name: temperature_in_celsius
        targets:
          - node_names: [ emulation ]
            asset_names: [ asset0 ]
      - data_type: raw.int32
        name: temperature_in_celsius_int
        targets:
          - node_names: [ emulation ]
            asset_names: [ asset0 ]
      - data_type: raw.float32
        name: measure_in_cm
        targets:
          - node_names: [ emulation ]
            asset_names: [ asset0 ]
      - data_type: raw.int32
        name: measure_in_cm_int
        targets:
          - node_names: [ emulation ]
            asset_names: [ asset0 ]
    system_packages:
      - vim
  type: kelvin
info:
  description: Data Producer
  name: producer
  title: Data Producer
  version: 1.2.1
spec_version: 4.0.0
