app:
  kelvin:
    core:
      connections:
        - name: myconnection
          type: opcua
          opcua:
            endpoint: opc.tcp://weathersource:48010
            registry_map:
              inputs:
                - access: RW
                  historize: false
                  name: weather
                  node: ns=2;s=weather
                  upload: false
                - access: RW
                  historize: false
                  name: wind
                  node: ns=2;s=wind
                  upload: false
              outputs: [ ]
              parameters: [ ]
      inputs:
        - data_model: weather.metric
          name: weather
          values: [ ]
        - data_model: raw.float32
          name: wind
          values: [ ]
      data_models:
        - name: 'weather.metric'
          version: 0.0.1
          path: 'datamodel/weather_metric__0-0-1.yml'
        - name: 'raw.float32'
          version: 2.0.0
      interface:
        client:
          args: [ ]
          executable: run_app
          period: 1.0
          spawn: true
        type: client
      language:
        python:
          entry_point: weather_custom_datamodel.weather_custom_datamodel:App
          requirements: requirements.txt
        type: python
      logging_level: INFO
      runtime:
        historize_inputs: false
        historize_outputs: true
        type: opcua
      version: 4.0.0
      configuration:
        - name: kelvin.app
          data_model: kelvin.app
          values:
            - name: offset_timestamps
              value: true
    images:
      base: ''
      builder: ''
    system_packages: [ ]
  type: kelvin
info:
  description: weather-custom-datamodel
  name: weather-custom-datamodel
  title: weather-custom-datamodel
  version: 1.0.0
spec_version: 1.0.0
