app:
  kelvin:
    data_types:
      - name: weather.metric
        path: datamodel/weather_metric__0-0-1.yml
        version: 0.0.1
    inputs:
      - data_type: weather.metric
        name: weather
        sources:
          - asset_names: []
            workload_names: []
      - data_type: raw.float32
        name: wind
        sources:
          - asset_names: []
            workload_names: []
    language:
      python:
        entry_point: weather_custom_datamodel.weather_custom_datamodel:App
        requirements: requirements.txt
      type: python
  type: kelvin
info:
  description: weather-custom-datamodel
  name: weather-custom-datamodel
  title: weather-custom-datamodel
  version: 1.0.0
spec_version: 2.0.0
