name: kelvin.producer
class_name: Producer
description: Producer Configuration Data-Model
fields:
  - description: Enable/Disable
    name: enabled
    type: boolean
  - description: Min Random Value
    name: min
    type: float32
  - description: Max Random Value
    name: max
    type: float32
version: 2.0.1
