app:
  kelvin:
    data_types: []
    language:
      python:
        entry_point: shared_file_reader.shared_file_reader:App
        requirements: requirements.txt
      type: python
  type: kelvin
info:
  description: shared-file-reader
  name: shared-file-reader
  title: shared-file-reader
  version: 1.0.0
spec_version: 2.0.0
system:
  privileged: false
  resources:
    cpu: '0.1'
    memory: 256Mi
  volumes:
    - host:
        source: /shared-data
      name: shared-data
      target: /shared-data
      type: text
