app:
  docker:
    args: []
    context: .
    dockerfile: Dockerfile
  type: docker
info:
  description: my description
  name: flask-server
  title: flask-server
  version: 1.0.0
spec_version: 2.0.0
