app:
  docker:
    args: []
    context: .
    dockerfile: Dockerfile
  type: docker
info:
  description: my description
  name: flask-server
  title: flask-server
  version: 1.0.0
spec_version: 4.0.0
system:
  ports:
    - name: http
      type: host
      host:
        port: 5000
  privileged: false
