app:
  kelvin:
    core:
      connections:
        - name: myconnection
          type: opcua
          opcua:
            endpoint: opc.tcp://weathersource:48010
            registry_map:
              inputs:
                - access: RW
                  historize: false
                  name: temperature
                  node: ns=2;s=temperature
                  upload: false
                - access: RW
                  historize: false
                  name: humidity
                  node: ns=2;s=humidity
                  upload: false
              outputs: [ ]
              parameters: [ ]
        - name: myconnection-out
          type: opcua
          opcua:
            endpoint: opc.tcp://weatherout:48010
            registry_map:
              inputs: [ ]
              outputs:
                - access: RW
                  historize: false
                  name: temperature_mean
                  node: ns=2;s=temperature_mean
                  upload: false
                - access: RW
                  historize: false
                  name: humidity_mean
                  node: ns=2;s=humidity_mean
                  upload: false
              parameters: [ ]
      data_models:
        - name: raw.float32
          version: 2.0.0
      inputs:
        - data_model: raw.float32
          name: temperature
          values: [ ]
        - data_model: raw.float32
          name: humidity
          values: [ ]
      outputs:
        - data_model: raw.float32
          name: temperature_mean
          values: [ ]
        - data_model: raw.float32
          name: humidity_mean
          values: [ ]
      interface:
        client:
          args: [ ]
          executable: run_app
          period: 1.0
          spawn: true
        type: client
      language:
        python:
          entry_point: weather.weather:App
          requirements: requirements.txt
        type: python
      logging_level: INFO
      runtime:
        historize_inputs: false
        historize_outputs: true
        type: opcua
      version: 4.0.0
      configuration:
        - name: kelvin.app
          data_model: kelvin.app
          values:
            - name: offset_timestamps
              value: true
    images:
      base: ''
      builder: ''
    system_packages: [ ]
  type: kelvin
info:
  description: weather
  name: weather
  title: weather
  version: 1.0.0
spec_version: 1.0.0
