app:
  kelvin:
    configuration:
      - name: kelvin.app
        data_model: kelvin.app
        values:
          - name: topics
            value:
              "#":
                target: "{name}"
                storage_type: buffer
                storage_config:
                  getter: value
                  window:
                    seconds: 5
          - name: checks
            value:
              "gas_flow":
                min_count: 3
              "valve_state":
                min_count: 3
    inputs:
      - data_type: raw.float32
        name: gas_flow
        sources:
          - asset_names: [ emulation ]
      - data_type: raw.float32
        name: valve_state
        sources:
          - asset_names: [ emulation ]
    language:
      python:
        entry_point: valve_malfunction.valve_malfunction:App
        requirements: requirements.txt
      type: python
    outputs:
      - data_type: raw.float32
        name: valve_malfunction
        targets:
          - asset_names: [ ]
            workload_names: [ ]
  type: kelvin
info:
  description: valve-malfunction
  name: valve-malfunction
  title: valve-malfunction
  version: 1.0.0
spec_version: 2.0.0
